### PR TITLE
Update command-line.md

### PR DESCRIPTION
**Pull request by komorita000**
If user account is not logged in, it won’t be able to connect. Also the tool only opens the file, and connects the editor (which is not working currently).. user would have to execute it manually.

Removed note about authentication because it was misleading to users.
And add note about script.

### CODE REVIEW

**Comment by ShannonLeavitt** [comment]
@rwestMSFT

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rwestMSFT** [comment]
Checking with product group. Generally we don't document things like your first suggestion, and I need to confirm the deletion.

**Comment by rwestMSFT** [comment]
We're going to incorporate your suggested changes into an internal PR. There is some additional context around this that is missing, and when that PR is merged, this one will automatically close. You will still get credit for your change.

**Comment by rwestMSFT** [comment]
The updated article will be published in the next few hours. Thank you for your contribution.

**Pull request closed without merging**
